# Generated by Django 4.0.2 on 2024-05-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='picture',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='icon',
            field=models.CharField(max_length=200),
        ),
    ]
