# Generated by Django 4.0.2 on 2024-05-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindup', '0006_meetingtag_meeting_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='meeting_members_set', to='mindup.Guest'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='meeting_tags_set', to='mindup.MeetingTag'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='organization_members_set', to='mindup.Guest'),
        ),
    ]
