# Generated by Django 4.0.2 on 2024-05-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindup', '0010_meeting_is_max_members_number_limited'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='origin_password',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
