# Generated by Django 4.0.2 on 2024-05-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ilya', max_length=50)),
                ('sur_name', models.CharField(default='Rybin', max_length=50)),
                ('last_name', models.CharField(default='Vladislavovich', max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('icon', models.URLField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindup.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('picture', models.URLField()),
                ('place_text', models.CharField(max_length=10000)),
                ('place_link', models.URLField(max_length=10000)),
                ('event_time', models.DateTimeField(verbose_name='event time')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindup.guest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindup.organization')),
            ],
        ),
    ]
