# Generated by Django 4.0.2 on 2024-05-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindup', '0002_alter_meeting_picture_alter_organization_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(default='-', max_length=10000),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='picture',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='place_link',
            field=models.URLField(default='-', max_length=10000),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='place_text',
            field=models.CharField(default='-', max_length=10000),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(default='-', max_length=10000),
        ),
        migrations.AlterField(
            model_name='organization',
            name='icon',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
