# Generated by Django 4.0.2 on 2024-05-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindup', '0003_alter_meeting_description_alter_meeting_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(related_name='meeting_members_set', to='mindup.Guest'),
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organization_members_set', to='mindup.Guest'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mindup.guest'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mindup.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mindup.guest'),
        ),
    ]
