# Generated by Django 4.0.2 on 2024-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindup', '0004_meeting_members_organization_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='max_members_number',
            field=models.IntegerField(default=0),
        ),
    ]
