# Generated by Django 4.0.2 on 2024-05-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindup', '0005_meeting_max_members_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='tags',
            field=models.ManyToManyField(related_name='meeting_tags_set', to='mindup.MeetingTag'),
        ),
    ]
