# Generated by Django 4.0.2 on 2024-05-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindup', '0007_alter_meeting_members_alter_meeting_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='description',
            field=models.CharField(default='-', max_length=10000),
        ),
    ]
