# Generated by Django 4.0.2 on 2024-05-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindup', '0008_guest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='place_link',
            field=models.URLField(default='https://www.youtube.com/watch?v=9CkE8pfJdkU', max_length=10000),
        ),
    ]
