# Generated by Django 4.0.2 on 2024-05-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindup', '0009_alter_meeting_place_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_max_members_number_limited',
            field=models.BooleanField(default=True),
        ),
    ]
